apiVersion: v1
kind: Namespace
metadata:
  name: etherpad-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: etherpad-app-test-latest
  namespace: etherpad-test
spec:
  type: GitHub
  pathname: https://github.com/heimdallreport/rhacm-labs.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: etherpad-app-test
  namespace: etherpad-test
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - etherpad-app-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: etherpad-app-test
  namespace: etherpad-test
  labels:
    app: etherpad-app-test
  annotations:
    apps.open-cluster-management.io/github-path: resources/etherpad
spec:
  channel: etherpad/etherpad-app-test-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: etherpad-test
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev

